

-- ***** LABORATÓRIO 1 ***** 

---A – Criando tipo de dados

-- 1. Coloque o banco PEDIDOS em uso;

-- 2. Crie os seguintes UDDTs
 /*
 TIPO_CODIGO  INT  NOT NULL
 TIPO_ENDERECO  VARCHAR(60) NULL
 TIPO_FONE  CHAR(14) NULL
 TIPO_SEXO  CHAR(1)  NOT NULL
 TIPO_ALIQUOTA  NUMERIC(4,2) NULL
 TIPO_PRAZO  INT  NOT NULL 
*/

-- Resposta:

 CREATE TYPE TIPO_CODIGO
 FROM INT NOT NULL;
 CREATE TYPE TIPO_ENDERECO
 FROM VARCHAR(60) NOT NULL;
 CREATE TYPE TIPO_FONE
 FROM CHAR(14) NOT NULL;
 CREATE TYPE TIPO_SEXO
 FROM CHAR(1) NOT NULL;
 CREATE TYPE TIPO_ALIQUOTA
 FROM NUMERIC(4,2) NULL;
 CREATE TYPE TIPO_PRAZO
 FROM INT NOT NULL;

-- 3. Crie a tabela PESSOAS, seguindo o modelo adiante:
 /*
 PESSOAS
 
 COD_PESSOA TIPO_CODIGO autonumeração chave 
primária
 NOME  VARCHAR(30)
 ENDERECO TIPO_ENDERECO
 SEXO  TIPO_SEXO
 
*/

-- Resposta:
 CREATE TABLE PESSOAS
 ( COD_PESSOA TIPO_CODIGO IDENTITY(1,1) PRIMARY KEY
  ,NOME VARCHAR(30)
  ,ENDERECO TIPO_ENDERECO
  ,SEXO TIPO_SEXO )

--4. Crie uma CONSTRAINT CHECK para o campo SEXO permitindo 
apenas valores F e M;
 ALTER TABLE PESSOAS 
ADD CONSTRAINT CK_PESSOAS_SEXO CHECK (SEXO IN (‘F’, ‘M’))

--5. Crie a tabela CONTAS, seguindo o modelo adiante:
 /* 
 CONTAS
 COD_CONTA TIPO_CODIGO autonumeração chave primária
 VALOR  NUMERIC(10,2)
 QTD_PARCELAS TIPO_PRAZO
 PORC_MULTA TIPO_ALIQUOTA
 */

-- Resposta: 
CREATE TABLE CONTAS
 ( COD_CONTA TIPO_CODIGO IDENTITY(1,1) PRIMARY KEY
  ,VALOR NUMERIC(10,2)
  ,QTD_PARCELAS TIPO_PRAZO
  ,PORC_MULTA TIPO_ALIQUOTA )
 

--6. Crie as CONSTRAINTS  CHECK para a tabela CONTAS:
 /*- Valor maior que zero- Quantidade de parcelas maior igual a 1
 - Percentual de multa maior igual a zero
 */
 ALTER TABLE CONTAS ADD CONSTRAINT CK_CONTAS_VALOR_MAIOR_ZERO 
CHECK (VALOR>0)
 ALTER TABLE CONTAS ADD CONSTRAINT CK_CONTAS_PARCELAS_MAIOR_
 IGUAL_1 CHECK (QTD_PARCELAS>=1)
 ALTER TABLE CONTAS ADD CONSTRAINT CK_CONTAS_PORC_MULTA CHECK 
(PORC_MULTA>=0)


--7. Crie a CONSTRAINT DEFAULT com valor 1 para o campo 
quantidade de parcelas
 ALTER TABLE CONTAS ADD CONSTRAINT DF_CONTAS_QTD_PARCELAS 
DEFAULT (1) FOR QTD_PARCELAS


--8. Crie a tabela Funcionario, seguindo o modelo adiante:
 /*
 Funcionario
 COD_FUNC  TIPO_CODIGO     chave primária,
 NOME   VARCHAR(30)
 ENDERECO  VARCHAR(80)
 SEXO   TIPO_SEXO 
*/
 CREATE TABLE FUNCIONARIO 
(
 COD_FUNC TIPO_CODIGO PRIMARY KEY
 ,NOME VARCHAR(30)
 ,ENDERECO VARCHAR(80)
 ,SEXO TIPO_SEXO )

 
--9. Crie um sinônimo de nome tb_Funcionario para a tabela FUNCIONARIO. 
CREATE SYNONYM TB_FUNCIONARIO FOR DBO.FUNCIONARIO 


--10. Crie uma SEQUENCE de nome SQ_FUNCIONARIO, que inicie em 100 com incremento 2.
 CREATE SEQUENCE SQ_FUNCIONARIO
 START WITH 100
 INCREMENT BY 2

--11. Crie um tipo de dados tabular com as informações:
 /*- Nome:  TIPO_FORNECEDOR- Campos:  ID_FORNECEDOR
  Nome do fornecedor
  Cidade
  Estado*/
 CREATE TYPE TIPO_FORNECEDOR AS TABLE
 (
 ID_FORNECEDOR INT
    ,NOME VARCHAR(50)
 ,CIDADE VARCHAR(30)
 ,ESTADO CHAR(2)
 )

